services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: practise_backend
    ports:
      - "7727:7727"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: practise_frontend
    ports:
      - "7272:7272"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
