package com.example.backend.json;

public enum ErrorType {
    MISSING_SECTION,
    FONT_MISMATCH,
    MARGIN_MISMATCH,
    LINE_SPACING_ERROR,
    INDENT_ERROR,
    HEADER_STYLE_ERROR,
    PAGE_NUMBER_MISSING,
    TABLE_CAPTION_ERROR,
    FIGURE_CAPTION_ERROR,
    CONTENT_TITLE_MISMATCH,
    INVALID_LIST_FORMAT,
    FORMULA_ERROR,
    CITATION_ERROR
}
